server:
  port: 8080

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TESTDB;integratedSecurity=false;TrustServerCertificate=true # SQL Server URL
    username: sa # SQL Server username
    password: A1134050-bJeannette # SQL Server password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update # (Optional) This option automatically updates the database schema to match your entities.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        
        